name: ChandaV
favicon: null
layout_spectrum: 0.5681910130660981
typography_spectrum: 0.4049970244523138
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.009199630236253142
  lightness: 0.7312342571094632
  saturation: 0.1098851072601974
  rhythmicContrast: 0.31125123309902847
purpose: []
